[video]
width = 640
height = 480
fullscreen = false
scale = 1.0
fps = 60

[audio]
music = 1.0
sound = 1.0
mono = false

[controls.player1]
device = 0
backwards = 0
forwards = 3
up = 22
down = 18
jab = 17
cross = 19
hook = 24
upper = 20
dodge = 4
start = 58

[controls.player2]
device = -1
backwards = -1
forwards = -1
up = -1
down = -1
jab = -1
cross = -1
hook = -1
upper = -1
dodge = -1
start = -1

[debug]
log_inputs = false
log_state = true
draw_collisionboxes = true
draw_hitboxes = true
draw_geometryboxes = true
